### ISSUE TITLE
[BUG] - numpy overflow encountered in reduce

### ISSUE THREAD

**Issue by Zalfrin** [akanz1/klib#6]
Thanks for sharing this package, I'm loving it!

I did run into a bug today. When I try to run dist_plot on my dataset, I get the following message:

<snip>\numpy\core\_methods.py:160: RuntimeWarning:
overflow encountered in reduce

I isolated it down to one particular series in my dataframe. It's not one I really care about, but maybe someone else will run into it for a series they DO care about. Here's a describe() after running it through klib's data_cleaning function:

`df.created_at.describe()`
count    5.213400e+04
mean     1.610795e+12
std      4.225043e+08
min      1.609891e+12
25%      1.610552e+12
50%      1.610838e+12
75%      1.611198e+12
max      1.611274e+12
Name: created_at, dtype: float64

Meanwhile, info() reports something different:

`df.info()`
...
 2   created_at       52134 non-null  float32
...

Notice one reports float32 while the other says float64... Seems fishy.

I'm using miniconda on Windows 10.
conda v4.9.2
numpy v1.19.5
klib v0.1.0

If you need me to provide my dataset, I can do so.

**Comment by akanz1** [comment]
@Zalfrin I'm glad you like it and thank you for the detailed description of your issue.

Regarding the error: Try upgrading klib. v0.1.0 is pretty old and usually found on systems running python <3.7

If it doesn't work with the latest version (klib 0.1.5) please let me know and i'll look into it in detail :)

**Comment by Zalfrin** [comment]
Whoops, I had some pretty messy dependencies going. You're right, that environment was back on python 3.6.

I set up a new minimal environment, package versions are now:
python 3.9.2
klib 0.1.5
numpy 1.20.1

Still seems to be a problem in the latest klib:

> <snip>numpy\core\_methods.py:178: RuntimeWarning: overflow encountered in reduce
>   ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)

```
print(df.created_at.describe())
print(type(df.created_at[0]))
df.info()
```

Name: created_at, dtype: float64

<class 'numpy.float32'>

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52134 entries, 0 to 52133
Data columns (total 32 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----             
 2   created_at       52134 non-null  float32

Seems like the series thinks its a float64 while the dataframe and the numpy element itself think they're float32. 😕

**Comment by akanz1** [comment]
Thanks for the update @Zalfrin, I can't immediately think of a reason why that behavior would be the case. 

Could you make the relevant parts of your data available to me? From what I understand so far you're using klib.data_cleaning() and then klib.dist_plot() and the column "created_at" seems to contain UNIX timestamps that lead to an overflow when float32 dtype is used.

I'll try to reproduce it as soon as I find the time. :)

**Comment by Zalfrin** [comment]
Give this a try:
[created_on.zip](https://github.com/akanz1/klib/files/6115071/created_on.zip)

**Comment by akanz1** [comment]
@Zalfrin thanks for the data. I was able to reproduce the issue and narrow it down to the computation of the kurtosis using scipy. `scipy.stats.kurtosis(df_cleaned)`

If you check your plot created with `klib.dist_plot(df_cleaned)`, you should notice that the kurtosis becomes infinite. I was not able to identify exactly why the calculation of the kurtosis results in a RuntimeWarning using the cleaned_df but not using the original df.

Given the overflow warning, i suspect that for the computation of the kurtosis (see [here for scipy source](https://github.com/scipy/scipy/blob/v1.6.1/scipy/stats/stats.py#L1250-L1357)) the 32bit float is not large enough to hold intermediary results, since the already large initial values (your UNIX timestamps) are squared.

Ideally, you convert your timestamps to a datetime using `datetime.fromtimestamp(timestamp)` to avoid the overflow. Or simply ignore the warning since the kurtosis likely does not add much value in this situation.

I hope this helps!

**Comment by Zalfrin** [comment]
@akanz1 yep that makes sense. You're right, the analysis of this particular variable is not interesting, so the overflow doesn't bother me. But who knows, maybe some day someone will run into this with data that IS interesting. :grinning: Thanks for taking a look.
